main:
  - name: Bio
    url: /
    weight: 10

  - name: Scientific Outputs
    url: /publications/
    weight: 20

  - name: Experiences
    url: /experience/
    weight: 30

  - name: Activities
    url: /projects/activities/
    weight: 40

  - name: Collaborations
    url: /projects/collaborations/
    weight: 50

  - name: Miscellaneous
    url: /projects/
    weight: 60
